---
title: "Teaching"
description-meta: "Courses taught by Gabriella (Gaby) Aboulafia at Harvard University and MIT."
---

## Harvard University

**Primary Instructor**, HLTHPOL 3020: Graduate Reading Course for Political
Analysis (Harvard GSAS). Taught four doctoral students in a required weekly
seminar. Spring 2026.

**Teaching Fellow**, GHHP 99: Global Health and Health Policy Capstone with
Prof. David Cutler (Harvard College). Taught 12 undergraduate students in a
required weekly seminar. Spring 2026.

**Teaching Fellow**, API 201: Quantitative Analysis and Empirical Methods I with
Profs. Jonathan Borck and Teddy Svoronos (Harvard Kennedy School). Taught 20+
master's students in an optional weekly review session. Fall 2024, Fall 2025.

**Course Assistant**, API 201: Quantitative Analysis and Empirical Methods I
with Profs. Jonathan Borck, Sharad Goel, and Teddy Svoronos (Harvard Kennedy
School). Held weekly office hours for students and graded problem sets and
exams. Fall 2023.

## Massachusetts Institute of Technology

**Teaching Fellow**, 17.30: Making Public Policy with Prof. Andrea Campbell.
Taught 18 undergraduate students in a required weekly section. Fall 2025.
